url: https://hsujeremy.github.io

title: Jeremy Hsu
description: Personal site for Jeremy Hsu

nav-links:
  - name: Home
    url: /
    external: false
  - name: Courses
    url: /courses
    external: false
  - name: Blog
    url: /blog
    external: false

greeting_image: /assets/memoji-circular-favicon.png
greeting_text: Hello! I'm Jeremy, a student at Harvard studying Computer Science.

show_excerpts: false
excerpt_word_count: 70

# long date: April 20, 1969
long_date: false
# short date: Apr ‘69
short_date: true

# don't modify
defaults:
  - # applies the default layout to all files in the project
    scope:
      path: ""
    values:
      layout: "default"
  - # layout with smaller name on top
    scope:
      path: "courses"
    values:
      layout: "small_title"
  - # sets is_post=true for all blog posts
    scope:
      path: ""
      type: posts
    values:
      is_post: true
permalink: /:title # so we have /about instead of /about.html, and /blog-post instead of /2019-11-22-blog-post.html
sass:
  style: compressed # compress the CSS file generated from the SCSS styles file
